### ISSUE TITLE
Bug portal for blueprint dashed list inputs

### ISSUE THREAD

**Issue by gdolle** [MSO4SC/MSOPortal#18]
For example if the blueprint have an input list,
```
inputs
    job_hpc_modules:
        description: modules to load depending on the targeted machine
        default:
            - gcc/6.1.0
            - openmpi/1.10.2
            - singularity/2.4.2
```
In  `portal -> experiment tool -> create instance` I get as a default list `gcc/6.1.0,openmpi/1.10.2,singularity/2.4.2` which seems ok, but it seems the local yaml is not well generated then,
because when I run the job I get this output
```
Lmod has detected the following error: The following module(s) are unknown: ""
"c" "e" "g" "i" "m" "," "o" "." "1" "p" "s" "2" "u" "t" "6" "y" "4" "r" "a" "l"
"0" "n"

   Please check the spelling or version number. Also try "module spider ..."
```
Note that this works in the command line.

**Comment by gdolle** [comment]
This is linked to #17

**Comment by gdolle** [comment]
Ok good news, it seems just passing the input value as an array works
```
job_hpc_modules:[ 'gcc/6.1.0', 'openmpi/1.10.2', 'singularity/2.4.2']
```
At least via command line. I have still to test via the portal now.

**Comment by gdolle** [comment]
To be more precise, 
The default input must be a sequence as usual
```
inputs
    job_hpc_modules:
        description: modules to load depending on the targeted machine
        default:
            - gcc/6.1.0
            - openmpi/1.10.2
            - singularity/2.4.2
```
And the local must be 
```
job_hpc_modules:[ 'gcc/6.1.0', 'openmpi/1.10.2', 'singularity/2.4.2']
```
